region           = "us-east-1"
secretKey        = "iNhVo4uJBNpTlaiZKBso+oN9PN7QfRkPWV9M63U7"
accessKey        = "AKIAVRUVVFKW2PIVEIFI"
bucketName       = "bankleumilambdabucket"
deployRoleName   = "root_aws_role"
zipFile          = "zip"
codeObjectKey    = "app.zip"
sourceDir        = "../app"
outputPath       = "../app/Lambda_Function.zip"
lambdaName       = "Lambda_Function"
awsLambdaRuntime = "nodejs18.x"

